In [2]:
# import openrouteservice as ors
# import folium
# from shapely import geometry
# from shapely.geometry import Polygon, MultiPolygon
#
# client = ors.Client(key='5b3ce3597851110001cf6248971aa72d85c54387b65a72d6e34b294f')

In [3]:
# user input:
#https://overpass-turbo.eu/

In [4]:
# 01.11.2025

# /*
# This has been generated by the overpass-turbo wizard.
# The original search was:
# “transport”
# */
# [out:json][timeout:25];
# area["name"="Hannover"]["boundary"="administrative"]["admin_level"="6"]->.searchArea;
# // gather results
# (
#   way["public_transport"="platform"]["tram"="yes"]({{bbox}});
#   relation["public_transport"="platform"]["tram"="yes"]({{bbox}});
# );
# // print results
# out geom;

In [5]:
from platform import python_version

print(python_version())
import sys
print(sys.executable)

# check, ob ich in der richtigen venv (mvcnn) bin. Auf der Wandernadel-Venv klappt es nicht.
# Falls nicht, dann unter "Configure Jupyter Server" den richtigen auswählen.
# Falls es nicht übernimmt: Pycharm neustarten hilt.

3.9.19
/Users/mandy/miniforge3/envs/mvcnn/bin/python

In [377]:
# import fiona
import os

import geopandas as gpd
import pandas as pd
import folium
import json
import ast
import numpy as np
import shapely

pd.set_option('display.max_rows', 100)
gdf = gpd.read_file("opnv_hannover.geojson")

# Pfad zum Ordner mit deinen GeoJSON-Dateien
# folder_path = "./Tucholsky_data"  # z.B. "./geojsons"

# Alle GeoJSON-Dateien im Ordner finden
# geojson_files = [f for f in os.listdir(folder_path) if f.endswith(".geojson") or f.endswith(".json")]

# Liste für alle DataFrames
# gdfs = []
#
# for filename in geojson_files:
# file_path = os.path.join(folder_path, filename)

# Alles zusammenführen
# combined_gdf = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True))

In [7]:
gdf

,id,@id,alt_name,bench,bin,bus,by_night,check_date,colour,covered,...,tram,type,via,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,geometry
0,relation/10999,relation/10999,None,None,None,None,None,NaT,#F9B000,None,...,None,route,None,None,None,None,Q63350805,None,None,"MULTILINESTRING ((9.82203 52.32197, 9.82226 52..."
1,relation/11000,relation/11000,None,None,None,None,None,NaT,#E4003A,None,...,None,route,None,None,None,None,Q63345432,None,None,"MULTILINESTRING ((9.73448 52.38932, 9.73438 52..."
2,relation/11001,relation/11001,None,None,None,None,None,NaT,#E4003A,None,...,None,route,Laatzen,None,None,None,Q63344401,None,None,"MULTILINESTRING ((9.75443 52.43689, 9.75441 52..."
3,relation/11002,relation/11002,None,None,None,None,None,NaT,#E4003A,None,...,None,route,None,None,None,None,Q63345326,None,None,"MULTILINESTRING ((9.78122 52.41549, 9.78119 52..."
4,relation/11004,relation/11004,None,None,None,None,None,NaT,#76B82A,None,...,None,route,None,None,None,None,Q63348315,None,None,"MULTILINESTRING ((9.74281 52.37916, 9.74252 52..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,node/13231540295,node/13231540295,None,None,None,no,None,NaT,None,None,...,yes,None,None,yes,Hochbahnsteig,None,None,None,None,POINT (9.66962 52.35444)
466,node/5920367910,node/5920367910,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""platform"", ""rel"": 11009, ""reltags...",POINT (9.71428 52.36646)
467,node/6497285746,node/6497285746,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""platform"", ""rel"": 3038599, ""relta...",POINT (9.71525 52.36674)
468,node/11767443138,node/11767443138,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 4099217, ""reltags"":...",POINT (9.73274 52.42395)
469,node/11767443137,node/11767443137,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 4099218, ""reltags"":...",POINT (9.7327 52.42394)

In [8]:
homebase = [9.7383162, 52.3744377]

gdf.sort_values('name')

,id,@id,alt_name,bench,bin,bus,by_night,check_date,colour,covered,...,tram,type,via,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,geometry
396,node/3700716416,node/3700716416,None,None,None,None,None,NaT,None,None,...,None,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2951395, ""reltags"":...",POINT (9.74341 52.36895)
395,node/3700716415,node/3700716415,None,None,None,None,None,NaT,None,None,...,None,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 10999, ""reltags"": {...",POINT (9.74342 52.36896)
394,node/3700716414,node/3700716414,None,None,None,None,None,NaT,None,None,...,None,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11000, ""reltags"": {...",POINT (9.74319 52.36889)
393,node/3700716413,node/3700716413,None,None,None,None,None,NaT,None,None,...,None,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",POINT (9.7432 52.3689)
215,node/1635653139,node/1635653139,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11012, ""...",POINT (9.66476 52.37711)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,node/2286795100,node/2286795100,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11001, ""reltags"": {...",POINT (9.73278 52.42303)
466,node/5920367910,node/5920367910,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""platform"", ""rel"": 11009, ""reltags...",POINT (9.71428 52.36646)
467,node/6497285746,node/6497285746,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""platform"", ""rel"": 3038599, ""relta...",POINT (9.71525 52.36674)
468,node/11767443138,node/11767443138,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 4099217, ""reltags"":...",POINT (9.73274 52.42395)
469,node/11767443137,node/11767443137,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 4099218, ""reltags"":...",POINT (9.7327 52.42394)

In [9]:
# 0. Explode:
#gdf[gdf['name']=='Linie 7: Wettbergen → Misburg'].explode().geometry.
# gdf[gdf['name']=='Linie 6: Messe/Ost (EXPO-Plaza) → Nordhafen'].explode().dissolve(by='name', as_index=False).plot()
#gdf.explode().dissolve(by='name', as_index=False, aggfunc='first')#.plot()
# gdf[gdf['name']=='Linie 6: Messe/Ost (EXPO-Plaza) → Nordhafen'].explode().dissolve(by='name')#.iloc[[0]]
#.dissolve(by='name', )#.iloc[[0]].plot()

# für Stationen:
# mehrere zusammenfassen




gdf[gdf['name']=='Linie 6: Messe/Ost (EXPO-Plaza) → Nordhafen'].explode().agg(lambda x: x.iloc[0])
gdf.explode().groupby(by='name').agg(lambda x: x.iloc[0])
# gdf.groupby(by='name')[['name','geometry']].explode().agg(lambda x: x.iloc[0])

,id,@id,alt_name,bench,bin,bus,by_night,check_date,colour,covered,...,tram,type,via,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,geometry
name,,,,,,,,,,,,,,,,,,,,,
Aegidientorplatz,node/3700716413,node/3700716413,None,None,None,None,None,NaT,None,None,...,None,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",POINT (9.7432 52.3689)
Ahlem,node/1635653139,node/1635653139,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11012, ""...",POINT (9.66476 52.37711)
Allerweg,node/3117171644,node/3117171644,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2998732, ""reltags"":...",POINT (9.72192 52.36215)
Alte Heide,node/1343306077,node/1343306077,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11002, ""...",POINT (9.78083 52.41557)
Altenbekener Damm,node/96716127,node/96716127,None,None,None,None,None,NaT,None,None,...,None,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",POINT (9.75459 52.3549)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wissenschaftspark Marienwerder,node/287015667,node/287015667,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2951396, ""reltags"":...",POINT (9.63369 52.41621)
Wunstorfer Straße,node/29364435,node/29364435,None,yes,yes,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11012, ""reltags"": {...",POINT (9.69509 52.37522)
Zehlendorfweg,node/248004234,node/248004234,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2998554, ""reltags"":...",POINT (9.75863 52.41967)
Zoo,node/137703451,node/137703451,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,Hochbahnsteig,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11010, ""...",POINT (9.76671 52.38118)
Zuschlagstraße,node/243056543,node/243056543,None,None,None,None,None,NaT,None,None,...,yes,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 10999, ""reltags"": {...",POINT (9.7926 52.35682)

In [10]:
# 1. Stationen und Linien unterscheiden
gdf['is_line']=gdf['name'].str.startswith('Linie')

gdf_lines = gdf[gdf['is_line']==True]
gdf_stations = gdf[gdf['is_line']==False]


# 2. Stationen mit dem selben Namen zusammenfassen und Centroid bestimmen.
# mehrere Zeilen einer Stationen zusammenfassen:
gdf_stations = gdf_stations.dissolve(by='name', as_index=False)

# aus dem zusammengefassten das Zentrum bestimmen
gdf_stations["center"] = gdf_stations.to_crs('epsg:3785').centroid.to_crs(gdf_stations.crs)


# 3. Aus den Linien nur das erste Element der Geometry rausziehen (die restlichen sind dann glaube ich die Bahnsteige..)
gdf_lines = gdf_lines.explode().groupby(by='name', as_index=False).first()#.plot()
# Beispiel-Plot der ersten 6 Linien:
#gdf_lines.iloc[0:6,:].plot()

In [11]:
gdf_stations

,name,geometry,id,@id,alt_name,bench,bin,bus,by_night,check_date,...,type,via,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,is_line,center
0,Aegidientorplatz,"MULTIPOINT (9.74319 52.36889, 9.7432 52.3689, ...",node/3700716413,node/3700716413,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",False,POINT (9.74331 52.36893)
1,Ahlem,"MULTIPOINT (9.66476 52.37714, 9.66476 52.37711)",node/1635653139,node/1635653139,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11012, ""...",False,POINT (9.66476 52.37712)
2,Allerweg,"MULTIPOINT (9.72188 52.36216, 9.72192 52.36215)",node/3117171644,node/3117171644,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2998732, ""reltags"":...",False,POINT (9.7219 52.36216)
3,Alte Heide,"MULTIPOINT (9.78078 52.41546, 9.78083 52.41557)",node/1343306077,node/1343306077,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11002, ""...",False,POINT (9.7808 52.41551)
4,Altenbekener Damm,"MULTIPOINT (9.75451 52.35488, 9.75459 52.3549)",node/96716127,node/96716127,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",False,POINT (9.75455 52.35489)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Wissenschaftspark Marienwerder,"MULTIPOINT (9.63369 52.41621, 9.63372 52.41617)",node/287015667,node/287015667,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2951396, ""reltags"":...",False,POINT (9.63371 52.41619)
200,Wunstorfer Straße,"MULTIPOINT (9.69509 52.37522, 9.6952 52.37524)",node/29364435,node/29364435,None,yes,yes,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11012, ""reltags"": {...",False,POINT (9.69514 52.37523)
201,Zehlendorfweg,"MULTIPOINT (9.75863 52.41967, 9.75974 52.41947)",node/248004234,node/248004234,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2998554, ""reltags"":...",False,POINT (9.75919 52.41957)
202,Zoo,"MULTIPOINT (9.76671 52.38118, 9.7668 52.38119)",node/137703451,node/137703451,None,None,None,None,None,NaT,...,None,None,yes,Hochbahnsteig,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11010, ""...",False,POINT (9.76675 52.38118)
203,Zuschlagstraße,"MULTIPOINT (9.79255 52.35679, 9.7926 52.35682)",node/243056543,node/243056543,None,None,None,None,None,NaT,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 10999, ""reltags"": {...",False,POINT (9.79257 52.35681)

In [12]:
gdf.sort_values(by='name')#[gdf["name"]=='Schünemannplatz']

,id,@id,alt_name,bench,bin,bus,by_night,check_date,colour,covered,...,type,via,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,geometry,is_line
396,node/3700716416,node/3700716416,None,None,None,None,None,NaT,None,None,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2951395, ""reltags"":...",POINT (9.74341 52.36895),False
395,node/3700716415,node/3700716415,None,None,None,None,None,NaT,None,None,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 10999, ""reltags"": {...",POINT (9.74342 52.36896),False
394,node/3700716414,node/3700716414,None,None,None,None,None,NaT,None,None,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11000, ""reltags"": {...",POINT (9.74319 52.36889),False
393,node/3700716413,node/3700716413,None,None,None,None,None,NaT,None,None,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",POINT (9.7432 52.3689),False
215,node/1635653139,node/1635653139,None,None,None,None,None,NaT,None,None,...,None,None,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11012, ""...",POINT (9.66476 52.37711),False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,node/2286795100,node/2286795100,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11001, ""reltags"": {...",POINT (9.73278 52.42303),None
466,node/5920367910,node/5920367910,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,"[ { ""role"": ""platform"", ""rel"": 11009, ""reltags...",POINT (9.71428 52.36646),None
467,node/6497285746,node/6497285746,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,"[ { ""role"": ""platform"", ""rel"": 3038599, ""relta...",POINT (9.71525 52.36674),None
468,node/11767443138,node/11767443138,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 4099217, ""reltags"":...",POINT (9.73274 52.42395),None
469,node/11767443137,node/11767443137,None,None,None,None,None,NaT,None,None,...,None,None,None,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 4099218, ""reltags"":...",POINT (9.7327 52.42394),None

In [13]:
# hier aus den Stationen, die in der Spalte "@relations" ein json-Dict stehen haben, die Linien-Nummern und Farben extrahieren.
# Danach wieder an den Original-gdf_stations dranjoinen.

# Beispiel:
# für eine Zeile aus dem gdf_stations die verschiedenen Tags + Values schön ausgeben:
# from pprint import pprint
# xyz = gdf_stations[gdf_stations["name"]=='Kröpcke']["@relations"].iloc[0]
# xyz
# pprint(json.loads(xyz))

# Beispiel:
# alle Keys für eine exemplarische Zeile printen (ohne values)
# xyz = gdf_stations[gdf_stations["name"]=='Kröpcke']["@relations"].iloc[0
# def get_all_keys(obj, prefix=""):
#     keys = set()
#     if isinstance(obj, dict):
#         for k, v in obj.items():
#             new_prefix = f"{prefix}.{k}" if prefix else k
#             keys.add(new_prefix)
#             keys |= get_all_keys(v, new_prefix)
#     elif isinstance(obj, list):
#         for i, item in enumerate(obj):
#             keys |= get_all_keys(item, prefix)
#     return keys
# data = json.loads(xyz)
# keys = get_all_keys(data)
# for k in sorted(keys):
#     print(k)


def extract_colour_ref_list(stations):

    gdf_stations = stations[["name","@relations"]].dropna()

    def loads_fuzzy(s):
        if isinstance(s, (list, dict)):
            return s
        try:
            return json.loads(s)
        except Exception:
            return ast.literal_eval(s)


    col = "@relations"
    parsed = gdf_stations[col].apply(loads_fuzzy)
    parsed

    expl = gdf_stations.drop(columns=[col]).join(
        pd.Series(parsed, index=gdf_stations.index, name="parsed")
    ).explode("parsed", ignore_index=False)


    # Felder ziehen
    expl["reltags_colour"] = expl["parsed"].apply(
        lambda d: ((d or {}).get("reltags", {}) or {}).get("colour")
                  or ((d or {}).get("reltags", {}) or {}).get("color")
    )
    expl["reltags_ref"] = expl["parsed"].apply(
        lambda d: ((d or {}).get("reltags", {}) or {}).get("ref")
    )

    # expl[["name","reltags_ref","reltags_colour"]]
    result_long = expl.drop(columns=["parsed"]).drop_duplicates().sort_values("reltags_ref")#
    result_long
    agg_back = (result_long
                .groupby("name", as_index=False)
                .agg(reltags_colours=("reltags_colour", lambda s: [x for x in s if pd.notna(x)]),
                     reltags_refs=("reltags_ref",     lambda s: [x for x in s if pd.notna(x)]))
               )

    agg_back
    df_joined = stations.merge(agg_back, on="name", how="left")
    return df_joined

In [14]:
gdf_stations = extract_colour_ref_list(gdf_stations)
gdf_stations

,name,geometry,id,@id,alt_name,bench,bin,bus,by_night,check_date,...,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,is_line,center,reltags_colours,reltags_refs
0,Aegidientorplatz,"MULTIPOINT (9.74319 52.36889, 9.7432 52.3689, ...",node/3700716413,node/3700716413,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",False,POINT (9.74331 52.36893),"[#E4003A, #E4003A, #E4003A]","[1, 2, 8]"
1,Ahlem,"MULTIPOINT (9.66476 52.37714, 9.66476 52.37711)",node/1635653139,node/1635653139,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11012, ""...",False,POINT (9.66476 52.37712),"[#76B82A, #76B82A]","[10, 12]"
2,Allerweg,"MULTIPOINT (9.72188 52.36216, 9.72192 52.36215)",node/3117171644,node/3117171644,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2998732, ""reltags"":...",False,POINT (9.7219 52.36216),"[#0069B4, #76B82A, #0069B4, #0069B4]","[13, 17, 3, 7]"
3,Alte Heide,"MULTIPOINT (9.78078 52.41546, 9.78083 52.41557)",node/1343306077,node/1343306077,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11002, ""...",False,POINT (9.7808 52.41551),[#E4003A],[2]
4,Altenbekener Damm,"MULTIPOINT (9.75451 52.35488, 9.75459 52.3549)",node/96716127,node/96716127,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",False,POINT (9.75455 52.35489),"[#E4003A, #E4003A, #E4003A]","[1, 2, 8]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Wissenschaftspark Marienwerder,"MULTIPOINT (9.63369 52.41621, 9.63372 52.41617)",node/287015667,node/287015667,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2951396, ""reltags"":...",False,POINT (9.63371 52.41619),[#F9B000],[4]
200,Wunstorfer Straße,"MULTIPOINT (9.69509 52.37522, 9.6952 52.37524)",node/29364435,node/29364435,None,yes,yes,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 11012, ""reltags"": {...",False,POINT (9.69514 52.37523),"[#76B82A, #76B82A]","[10, 12]"
201,Zehlendorfweg,"MULTIPOINT (9.75863 52.41967, 9.75974 52.41947)",node/248004234,node/248004234,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 2998554, ""reltags"":...",False,POINT (9.75919 52.41957),[#E4003A],[2]
202,Zoo,"MULTIPOINT (9.76671 52.38118, 9.7668 52.38119)",node/137703451,node/137703451,None,None,None,None,None,NaT,...,yes,Hochbahnsteig,None,None,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11010, ""...",False,POINT (9.76675 52.38118),[#F9B000],[11]
203,Zuschlagstraße,"MULTIPOINT (9.79255 52.35679, 9.7926 52.35682)",node/243056543,node/243056543,None,None,None,None,None,NaT,...,yes,None,None,None,None,"[ { ""role"": ""stop"", ""rel"": 10999, ""reltags"": {...",False,POINT (9.79257 52.35681),[#F9B000],[6]

In [15]:
# für die Linien zunächst die Koordinaten aus den Linestrings extrahieren
coords =  gdf_lines.groupby(by='name')['geometry'].agg(lambda x: x.get_coordinates(ignore_index=True)[['y','x']].values.tolist()).reset_index().rename(columns= {'geometry':'coordinates'})

# Koordinaten an den original gdf_lines dranjoinen:
gdf_lines = gdf_lines.merge(coords,on='name')

gdf_lines

,name,id,@id,alt_name,bench,bin,bus,by_night,check_date,colour,...,via,wheelchair,wheelchair:description,wheelchair:note,wikidata,wikimedia_commons,@relations,is_line,geometry,coordinates
0,Linie 10: Ahlem → Hauptbahnhof/ZOB,relation/11012,relation/11012,None,None,None,None,None,NaT,#76B82A,...,None,None,None,None,Q63348270,None,None,True,"LINESTRING (9.66476 52.37711, 9.66545 52.37712...","[[52.3771083, 9.664763], [52.377119, 9.6654497..."
1,Linie 10: Hauptbahnhof/ZOB → Ahlem,relation/3004805,relation/3004805,None,None,None,None,None,NaT,#76B82A,...,None,None,None,None,Q63348270,None,None,True,"LINESTRING (9.74281 52.37916, 9.74252 52.37903...","[[52.3791646, 9.7428051], [52.3790296, 9.74251..."
2,Linie 11: Haltenhoffstraße → Schlägerstraße,relation/8781479,relation/8781479,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350814,None,None,True,"LINESTRING (9.71282 52.39316, 9.71289 52.39314...","[[52.393161, 9.7128166], [52.3931444, 9.712886..."
3,Linie 11: Haltenhoffstraße → Zoo,relation/2991648,relation/2991648,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350814,None,None,True,"LINESTRING (9.71285 52.39322, 9.71292 52.3932,...","[[52.3932197, 9.712846], [52.3932026, 9.712919..."
4,Linie 11: Zoo → Haltenhoffstraße,relation/11010,relation/11010,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350814,None,None,True,"LINESTRING (9.71282 52.39316, 9.71289 52.39314...","[[52.393161, 9.7128166], [52.3931444, 9.712886..."
5,Linie 12: Ahlem → Hauptbahnhof,relation/3004830,relation/3004830,None,None,None,None,only,NaT,#76B82A,...,None,None,None,None,None,None,None,True,"LINESTRING (9.66476 52.37711, 9.66545 52.37712...","[[52.3771083, 9.664763], [52.377119, 9.6654497..."
6,Linie 12: Hauptbahnhof → Ahlem,relation/3004824,relation/3004824,None,None,None,None,only,NaT,#76B82A,...,None,None,None,None,None,None,None,True,"LINESTRING (9.75577 52.39157, 9.7549 52.39107,...","[[52.3915665, 9.7557654], [52.3910664, 9.75489..."
7,Linie 13: Fasanenkrug → Hemmingen,relation/16856342,relation/16856342,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63349759,None,None,True,"LINESTRING (9.80102 52.43153, 9.80112 52.43153...","[[52.431533, 9.8010214], [52.4315258, 9.801124..."
8,Linie 13: Hemmingen → Fasanenkrug,relation/16856367,relation/16856367,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63349759,None,None,True,"LINESTRING (9.72982 52.31642, 9.72965 52.31685...","[[52.3164233, 9.729816], [52.3168472, 9.729645..."
9,Linie 16: Königsworther Platz → Messe / Ost (E...,relation/8712351,relation/8712351,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q110253214,None,None,True,"LINESTRING (9.72281 52.3782, 9.72294 52.37813,...","[[52.378196, 9.7228092], [52.378129, 9.722941]..."
10,Linie 17: Hauptbahnhof/ZOB → Wallensteinstraße,relation/11004,relation/11004,None,None,None,None,None,NaT,#76B82A,...,None,None,None,None,Q63348315,None,None,True,"LINESTRING (9.74281 52.37916, 9.74252 52.37903...","[[52.3791646, 9.7428051], [52.3790296, 9.74251..."
11,Linie 17: Wallensteinstraße → Hauptbahnhof/ZOB,relation/2998732,relation/2998732,None,None,None,None,None,NaT,#76B82A,...,None,None,None,None,Q63348315,None,None,True,"LINESTRING (9.71839 52.34199, 9.71847 52.342, ...","[[52.3419922, 9.7183932], [52.3419989, 9.71846..."
12,Linie 18: Hauptbahnhof → Messe / Nord,relation/8712367,relation/8712367,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q107242125,None,None,True,"LINESTRING (9.73448 52.38932, 9.73438 52.38898...","[[52.3893224, 9.7344797], [52.3889808, 9.73438..."
13,Linie 1: Laatzen → Langenhagen,relation/4099217,relation/4099217,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63344401,None,None,True,"LINESTRING (9.81608 52.3028, 9.81553 52.30317,...","[[52.3028022, 9.8160765], [52.3031733, 9.81553..."
14,Linie 1: Langenhagen → Laatzen,relation/4099218,relation/4099218,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63344401,None,None,True,"LINESTRING (9.75443 52.43689, 9.75441 52.4369,...","[[52.4368948, 9.754434], [52.4369004, 9.754409..."
15,Linie 1: Langenhagen → Sarstedt,relation/11001,relation/11001,None,None,None,None,None,NaT,#E4003A,...,Laatzen,None,None,None,Q63344401,None,None,True,"LINESTRING (9.75443 52.43689, 9.75441 52.4369,...","[[52.4368948, 9.754434], [52.4369004, 9.754409..."
16,Linie 1: Sarstedt → Langenhagen,relation/2995651,relation/2995651,None,None,None,None,None,NaT,#E4003A,...,Laatzen,None,None,None,Q63344401,None,None,True,"LINESTRING (9.85783 52.23613, 9.85777 52.23624...","[[52.236131, 9.8578346], [52.2362388, 9.857768..."
17,Linie 2: Alte Heide → Gleidingen,relation/11002,relation/11002,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345326,None,None,True,"LINESTRING (9.78122 52.41549, 9.78119 52.4155,...","[[52.4154895, 9.781224], [52.415495, 9.7811949..."
18,Linie 2: Alte Heide → Laatzen / Ginsterweg,relation/10626404,relation/10626404,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345326,None,None,True,"LINESTRING (9.78122 52.41549, 9.78119 52.4155,...","[[52.4154895, 9.781224], [52.415495, 9.7811949..."
19,Linie 2: Alte Heide → Peiner Straße,relation/10626405,relation/10626405,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345326,None,None,True,"LINESTRING (9.78122 52.41549, 9.78119 52.4155,...","[[52.4154895, 9.781224], [52.415495, 9.7811949..."
20,Linie 2: Gleidingen → Alte Heide,relation/2998554,relation/2998554,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345326,None,None,True,"LINESTRING (9.83702 52.277, 9.83685 52.27718, ...","[[52.2769969, 9.8370151], [52.2771773, 9.83685..."
21,Linie 2: Peiner Straße → Alte Heide,relation/10626427,relation/10626427,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345326,None,None,True,"LINESTRING (9.76919 52.33754, 9.76902 52.33774...","[[52.3375392, 9.7691878], [52.3377396, 9.76901..."
22,Linie 3: Altwarmbüchen → Wettbergen,relation/11006,relation/11006,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63348707,None,None,True,"LINESTRING (9.84741 52.43778, 9.84744 52.43738...","[[52.4377783, 9.8474104], [52.4373816, 9.84744..."
23,Linie 3: Wettbergen → Altwarmbüchen,relation/3016070,relation/3016070,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63348707,None,None,True,"LINESTRING (9.69074 52.33276, 9.69075 52.3328,...","[[52.3327585, 9.690736], [52.3327969, 9.690748..."
24,Linie 4: Garbsen → Roderbruch,relation/2951395,relation/2951395,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350784,None,None,True,"LINESTRING (9.81909 52.39014, 9.81899 52.39011...","[[52.3901397, 9.8190928], [52.3901124, 9.81899..."
25,Linie 4: Roderbruch → Fuhsestraße/Bhf,relation/8682917,relation/8682917,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350784,None,None,True,"LINESTRING (9.81905 52.39019, 9.81893 52.39016...","[[52.390193, 9.8190522], [52.3901584, 9.818929..."
26,Linie 4: Roderbruch → Garbsen,relation/2951396,relation/2951396,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350784,None,None,True,"LINESTRING (9.81905 52.39019, 9.81893 52.39016...","[[52.390193, 9.8190522], [52.3901584, 9.818929..."
27,Linie 5: Anderten → Stöcken,relation/2583341,relation/2583341,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350794,None,None,True,"LINESTRING (9.85875 52.35839, 9.85834 52.35843...","[[52.3583895, 9.8587476], [52.3584315, 9.85834..."
28,Linie 5: Stöcken → Anderten,relation/2991700,relation/2991700,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350794,None,None,True,"LINESTRING (9.66725 52.41467, 9.66672 52.41464...","[[52.4146688, 9.6672537], [52.4146373, 9.66671..."
29,Linie 5: Stöcken → Fuhsestraße/Bhf,relation/8682878,relation/8682878,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350794,None,None,True,"LINESTRING (9.66725 52.41467, 9.66672 52.41464...","[[52.4146688, 9.6672537], [52.4146373, 9.66671..."
30,Linie 6: Messe/Ost (EXPO-Plaza) → Nordhafen,relation/10999,relation/10999,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350805,None,None,True,"LINESTRING (9.82203 52.32197, 9.82226 52.32217...","[[52.3219706, 9.8220348], [52.3221673, 9.82225..."
31,Linie 6: Nordhafen → Messe/Ost (EXPO-Plaza),relation/2991602,relation/2991602,None,None,None,None,None,NaT,#F9B000,...,None,None,None,None,Q63350805,None,None,True,"LINESTRING (9.69 52.42238, 9.69024 52.42218, 9...","[[52.4223763, 9.6900032], [52.4221784, 9.69024..."
32,Linie 7: Misburg → Wettbergen,relation/11005,relation/11005,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63348805,None,None,True,"LINESTRING (9.8538 52.39139, 9.8537 52.39143, ...","[[52.3913931, 9.8538033], [52.3914345, 9.85369..."
33,Linie 7: Wettbergen → Misburg,relation/3038574,relation/3038574,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63348805,None,None,True,"LINESTRING (9.69074 52.33276, 9.69075 52.3328,...","[[52.3327585, 9.690736], [52.3327969, 9.690748..."
34,Linie 8: Dragonerstraße → Messe / Nord,relation/8556968,relation/8556968,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345432,None,None,True,"LINESTRING (9.73527 52.39403, 9.73513 52.39344...","[[52.39403, 9.7352679], [52.3934366, 9.7351291..."
35,Linie 8: Hauptbahnhof → Messe / Nord,relation/11000,relation/11000,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345432,None,None,True,"LINESTRING (9.73448 52.38932, 9.73438 52.38898...","[[52.3893224, 9.7344797], [52.3889808, 9.73438..."
36,Linie 8: Messe / Nord → Dragonerstraße,relation/8556967,relation/8556967,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345432,None,None,True,"LINESTRING (9.8045 52.32779, 9.8047 52.32786, ...","[[52.3277889, 9.8045], [52.3278601, 9.8046954]..."
37,Linie 8: Messe / Nord → Hauptbahnhof,relation/2998721,relation/2998721,None,None,None,None,None,NaT,#E4003A,...,None,None,None,None,Q63345432,None,None,True,"LINESTRING (9.8045 52.32779, 9.8047 52.32786, ...","[[52.3277889, 9.8045], [52.3278601, 9.8046954]..."
38,Linie 9: Empelde → Hauptbahnhof,relation/11009,relation/11009,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63349759,None,None,True,"LINESTRING (9.66717 52.34392, 9.6677 52.34397,...","[[52.3439242, 9.667168], [52.3439728, 9.667704..."
39,Linie 9: Hauptbahnhof → Empelde,relation/3038599,relation/3038599,None,None,None,None,None,NaT,#0069B4,...,None,None,None,None,Q63349759,None,None,True,"LINESTRING (9.74288 52.3784, 9.74244 52.37784,...","[[52.3784002, 9.7428759], [52.377838, 9.742436..."

In [186]:
m = folium.Map(location=list(reversed(homebase)), tiles='cartodbpositron', zoom_start=13)

# Linien:
for _, line in gdf_lines.iterrows():
    my_PolyLine=folium.PolyLine(locations=line["coordinates"], weight=4,
                                color=line["colour"],
                                tooltip=line["name"])
    my_PolyLine.add_to(m)

# Stationen:
for _, r in gdf_stations.iterrows():
    lat = r["center"].y
    lon = r["center"].x

    # falls vorhanden, nimm immer die erste Farbe in der Liste:
    if isinstance(r["reltags_colours"], list) and len(r["reltags_colours"]) > 0:
        farbe_station= r["reltags_colours"][0]
        #print(f"name: {r['name']}, {farbe_station}")

    else:
       farbe_station =  "#000000"

    # Linien nach Nummern sortieren
    def sort_linerefs(refs):
        sorted_lines = sorted([int(x) for x in refs])
        return sorted_lines

    if isinstance(r["reltags_refs"], list):
        # sortiere als int, convert whole list to str and then entferne die Listen-Klammern hinten und vorne ([1:-1])
        lines =  str(sort_linerefs(r["reltags_refs"]))[1:-1]
    else:
        lines ="Keine Linien"

    folium.CircleMarker(
        location=[lat, lon],
        popup="<strong>{}</strong><br><br> Linien: {}".format(r["name"],lines),
        color=farbe_station,
        fill_color=farbe_station,
        fill_opacity=1,
        radius=4
    ).add_to(m)


# die Linien einzeichnen:
# check: TO DO: die verschiedenen Linien durchiterieren (aktuell wird nur die erste genutzt) + passend einfärben
# check: TO DO: Stationen als Punkte einzeichnen, nicht als Marker.
# check TO DO: pro Station schreiben, welche Linien dort fahren
# check TO DO: entsprechend dann die Punkte auch einfärben
# check TO DO: Linien im Popup sortieren
# To DO: Überlappende Linien vereinfachen (optional)

# weitere Ideen:
# Verschiedene Layer ("FeatureGroup", "LayerControl")
# Abgleich zur Netzkarte; Warping der Real-Karte hinterlegen

m

In [17]:
gdf_stations[gdf_stations["name"]=='Kröpcke']["reltags_refs"]




#key=lambda x: int(x) if str(x).isdigit() else str(x)

103    [12, 13, 3, 7, 9]
Name: reltags_refs, dtype: object

In [18]:
gdf_stations["name"]

0                    Aegidientorplatz
1                               Ahlem
2                            Allerweg
3                          Alte Heide
4                   Altenbekener Damm
                    ...
199    Wissenschaftspark Marienwerder
200                 Wunstorfer Straße
201                     Zehlendorfweg
202                               Zoo
203                    Zuschlagstraße
Name: name, Length: 204, dtype: object

## Auslesen des U-Bahn-Plans

In [332]:
#pip install pymupdf
import fitz  # PyMuPDF

In [333]:
# text_dict = page.get_text("dict", sort=True)
# words = page.get_text("words", sort=True)

In [336]:
#### Nur textweise / Beispiel.
### SEARCH
# text = "Vier Grenzen"
# text_instances = page.search_for(text)

# ### HIGHLIGHT
# for inst in text_instances:
#     highlight = page.add_highlight_annot(inst)
#     highlight.update()
doc = fitz.open("UESTRA_Netzplan-U_2024-25.pdf")
page = doc[0]  # es gibt nur eine Seite
page_rect = page.rect  # (x0,y0,x1,y1) im PDF-Koordi

displays = [fitz.Rect(0, 50, 0, 50)]


# iterate through each text using for loop and annotate
for disp in displays:
    rl = page.search_for("Auf der Horst/Marshof")#, quads = True)
    page.add_highlight_annot(rl)

# highlight = page.add_highlight_annot(displ)
# highlight.update()
#
# ### OUTPUT
doc.save("output.pdf", garbage=4, deflate=True, clean=True)

In [338]:
# Mapping der Stations-Namen aus dem Dataframe zur PDF-Datei

gdf_stations['name_netzplan'] = 'Noch nicht gesetzt'

# für Namen mit "Straße"--> Abkürzen
for index, row in gdf_stations.iterrows():
    if "aße"  in row["name"]:
        #print(row["name"])
        gdf_stations.at[index, 'name_netzplan'] = row["name"].replace("aße", ".")


# manuell hinzufügen:
gdf_stations.at[27, 'name_netzplan']='Bf. Linden/Fischerhof'
gdf_stations.at[36, 'name_netzplan']='Fuhse-str./Bhf.'
gdf_stations.at[69, 'name_netzplan']='Glocksee/Bhf'
gdf_stations.at[79, 'name_netzplan']='Hbf./ZOB'
gdf_stations.at[131, 'name_netzplan']='Markthalle/ Landtag'
gdf_stations.at[134, 'name_netzplan']='Messe/Nord'
gdf_stations.at[168, 'name_netzplan']='Schneiderberg/W.-Busch-Museum'
gdf_stations.at[78, 'name_netzplan']='Hbf./ Rosenstr.'
gdf_stations.at[45, 'name_netzplan']='Bünteweg/TiHo'
gdf_stations.at[7, 'name_netzplan']='Altwarmbüchen/ Zentrum'
gdf_stations.at[8, 'name_netzplan']='Altwarmbüchen/ Ernst-Grote-Str.'
gdf_stations.at[9, 'name_netzplan']='Altwarmbüchen/ Opelstr.'
gdf_stations.at[66, 'name_netzplan']='Gleid./Am Leinkamp'
gdf_stations.at[81, 'name_netzplan']='Heis./Marienburger Str.'
gdf_stations.at[112, 'name_netzplan']='Laatzen/ Ginsterweg'
gdf_stations.at[113, 'name_netzplan']='Laatzen/ Krankenhaus'
gdf_stations.at[114, 'name_netzplan']='Laatzen/ Neuer Schlag'
gdf_stations.at[115, 'name_netzplan']='Laatzen/ Park der Sinne'
gdf_stations.at[116, 'name_netzplan']='Laatzen/ Rethener Winkel'
gdf_stations.at[118, 'name_netzplan']='Laatzen/ aquaLaatzium'
gdf_stations.at[66, 'name_netzplan']='Gleidingen/ Am Leinkamp'
gdf_stations.at[80, 'name_netzplan']='Heisede/ Langer Kamp'
gdf_stations.at[122, 'name_netzplan']='Langenhagen/ Langenforther Platz'
gdf_stations.at[121, 'name_netzplan']='Langenhagen/ Kurt-Schumacher-Allee'
gdf_stations.at[123, 'name_netzplan']='Langenhagen/ Zentrum'
gdf_stations.at[44, 'name_netzplan']='Buchholz/Bhf.'
gdf_stations.at[156, 'name_netzplan']='Rethen/ Steinfeld'

#gdf_stations[gdf_stations["name_netzplan"]=='Noch nicht gesetzt']

In [339]:
# Bei den Stationsnamen, die direkt gefunden werden: kopiere den Namen in die Netzplan_name-Spalte
doc = fitz.open("UESTRA_Netzplan-U_2024-25.pdf")
page = doc[0]  # es gibt nur eine Seite
page_rect = page.rect

# gehe alle Stationen durch, markiere sie, wenn sie gefunden werden.
# Gebe aus, welche *nicht* gefunden wurden.

gdf_stations["quad_rect_text"] = 0#np.nan
for index, row in gdf_stations.iterrows():
    rl_name = page.search_for(row['name'], quads=True)
    rl_name_netzplan = page.search_for(row['name_netzplan'], quads=True)
    if len(rl_name)>0:
        # falls im Plan gefunden:
        # Stationsname im gdf hinzufügen
        gdf_stations.at[index, 'name_netzplan']=row['name']
        # print(rl_name[0].rect)
        gdf_stations.at[index, 'quad_rect_text']=rl_name[0].rect
        #print(f"{row['name']}:  {row['name_netzplan']}")
        # squiggly underline in pdf
        annot = page.add_squiggly_annot(rl_name[0])
        # annot = page.draw_circle(rl_name[0].ul, 2)
        # page.add_highlight_annot(rl_name[0].rect)

    elif len(rl_name_netzplan)>0:
        #print("Unter dem verkürzten Namen gefunden.")
        #print(f"{row['name']}:  {row['name_netzplan']}")
        gdf_stations.at[index, 'quad_rect_text']=rl_name_netzplan[0].rect
        annot = page.add_squiggly_annot(rl_name_netzplan[0])
        # page.add_highlight_annot(rl_name_netzplan[0].rect)
    else:
        if row["name_netzplan"]=='Noch nicht gesetzt':
            print(f"Station {row['name']} nicht gefunden (und auch noch nicht gesetzt).")
            pass
        else:
            #pass
            print(f"Station nicht gefunden, obwohl gesetzt. {row['name']}")

doc.save("output.pdf", garbage=4, deflate=True, clean=True)

/var/folders/st/kzjp030145z7_xvmpy7_l62h0000gn/T/ipykernel_35286/4042394481.py:18: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Rect(449.9623718261719, 317.350830078125, 491.6735534667969, 326.1135559082031)' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  gdf_stations.at[index, 'quad_rect_text']=rl_name[0].rect

Station nicht gefunden, obwohl gesetzt. Betriebshof Fuhsestraße
Station nicht gefunden, obwohl gesetzt. Gleidingen/Am Leinkamp
Station Hohenfels Nord Abfahrtshaltestelle nicht gefunden (und auch noch nicht gesetzt).
Station Hohenfels Süd nicht gefunden (und auch noch nicht gesetzt).

In [294]:
# Stations-Punkte extrahieren
doc = fitz.open("UESTRA_Netzplan-U_2024-25.pdf")
page = doc[0]  # es gibt nur eine Seite
page_rect = page.rect
cdrawings = page.get_cdrawings()#, sort=True)


circles = []
rects = []

# Parameter nach Bedarf anpassen
square_tol = 0.35      # max. 15% Abweichung von Quadrat
min_diam   = 1.85     # minimaler Durchmesser
max_diam   = 20.0      # maximaler Durchmesser

for d in cdrawings:
    # Nur gefüllte Pfade
    # if d.get("type") != "f":
    #     continue
    if d.get("type") not in ("f", "s", "fs"):
        continue

    items = d.get("items", [])
    if not items:
        continue

    #rects.append(d["rect"])
    # Nur Objekte betrachten, deren Items ausschließlich 'c' (Bezierkurven) sind
    if not all(item[0] == "c" for item in items):
        continue

    x0, y0, x1, y1 = d["rect"]
    w = x1 - x0
    h = y1 - y0
    if w <= 0 or h <= 0:
        continue

    # annähernd quadratisch?
    if abs(w - h) > max(w, h) * square_tol:
        continue

    # Größen-Filter (damit du nicht riesige Kreise / Flächen mit erwischst)
    if not (min_diam <= max(w, h) <= max_diam):
        continue

    # Mittelpunkt / Radius aus dem bounding rect
    cx = (x0 + x1) / 2.0
    cy = (y0 + y1) / 2.0
    r  = max(w, h) / 2.0

    if (min_diam <= r <= max_diam):

        #print(f"{cx}, {cy}")
        circles.append((cx,cy))
        rects.append(d["rect"])
        #print(r)

## Zusammenbringen von Netzplan und Dataframe

In [320]:
# für jede Zeile aus dem df: schauen, welcher Circle am nähesten ist.
import numpy as np

def dist_point_to_rect_edge(px, py, x0, y0, x1, y1):
    # sicherstellen, dass x0<x1, y0<y1
    if x0 > x1:
        x0, x1 = x1, x0
    if y0 > y1:
        y0, y1 = y1, y0

    inside_x = x0 <= px <= x1
    inside_y = y0 <= py <= y1

    # Punkt liegt im Rechteck → Abstand zum Rand
    if inside_x and inside_y:
        return min(px - x0, x1 - px, py - y0, y1 - py)

    # senkrecht zu einer horizontalen Kante
    if inside_x:
        return y0 - py if py < y0 else py - y1

    # senkrecht zu einer vertikalen Kante
    if inside_y:
        return x0 - px if px < x0 else px - x1

    # Ecke (außerhalb in x und y)
    dx = x0 - px if px < x0 else px - x1
    dy = y0 - py if py < y0 else py - y1
    return (dx**2 + dy**2) ** 0.5

points = circles #[(px1, py1), (px2, py2), ...]  # deine Punktliste

def nearest_point_to_rect_edge(rect_list):

    # falls Station nicht auf der Karte gefunden wurde (dann ist Spalte quad_rect_text=0
    if rect_list==0:
        return None, np.nan

    x0 = rect_list.x0
    y0 = rect_list.y0
    x1 = rect_list.x1
    y1 = rect_list.y1
    dists = [
        dist_point_to_rect_edge(px, py, x0, y0, x1, y1)
        for (px, py) in points
    ]
    idx = int(np.argmin(dists))
    return points[idx], dists[idx]


# rect_coords ist eine Liste [x0, y0, x1, y1] in jeder Zeile
gdf_stations["nearest_point"], gdf_stations["nearest_dist"] = zip(
    *gdf_stations["quad_rect_text"].apply(nearest_point_to_rect_edge)
)

In [331]:
### Die Stationen und die als nähesten Stationen-Punkte gefunenen Circle einzeichnen:

doc = fitz.open("UESTRA_Netzplan-U_2024-25.pdf")
page = doc[0]  # es gibt nur eine Seite
page_rect = page.rect

# gehe alle Stationen durch, markiere sie, wenn sie gefunden werden.
# Gebe aus, welche *nicht* gefunden wurden.

gdf_stations["quad_rect_text"] = 0#np.nan
for index, row in gdf_stations.iterrows():
    rl_name_netzplan = page.search_for(row['name_netzplan'], quads=True)#[0]
    if len(rl_name_netzplan)>0:
        # nähesten circle einzeichnen:
        page.draw_circle(fitz.Point(row['nearest_point']), 5, color=(1,0,0))

        # squiggly underline in pdf
        annot = page.add_squiggly_annot(rl_name_netzplan[0])

        # verbindungslinie zwischen dem quad und dem circ:
        page.draw_line(fitz.Point(row['nearest_point']), rl_name_netzplan[0].ul)#, color=(0,), width=1, dashes=None, lineCap=0, lineJoin=0, overlay=True, morph=None, stroke_opacity=1, fill_opacity=1, oc=0)

        # annot = page.draw_circle(rl_name[0].ul, 2)
        # page.add_highlight_annot(rl_name[0].rect)

doc.save("output.pdf", garbage=4, deflate=True, clean=True)

In [341]:
gdf_stations

,name,geometry,id,@id,alt_name,bench,bin,bus,by_night,check_date,...,wikimedia_commons,@relations,is_line,center,reltags_colours,reltags_refs,name_netzplan,quad_rect_text,nearest_point,nearest_dist
0,Aegidientorplatz,"MULTIPOINT (9.74319 52.36889, 9.7432 52.3689, ...",node/3700716413,node/3700716413,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",False,POINT (9.74331 52.36893),"[#E4003A, #E4003A, #E4003A]","[1, 2, 8]",Aegidientorplatz,"[449.9623718261719, 317.350830078125, 491.6735...","(470.64068603515625, 346.70091247558594)",20.587357
1,Ahlem,"MULTIPOINT (9.66476 52.37714, 9.66476 52.37711)",node/1635653139,node/1635653139,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11012, ""...",False,POINT (9.66476 52.37712),"[#76B82A, #76B82A]","[10, 12]",Ahlem,"[129.4739990234375, 308.75140380859375, 149.75...","(180.84369659423828, 318.67628479003906)",31.092979
2,Allerweg,"MULTIPOINT (9.72188 52.36216, 9.72192 52.36215)",node/3117171644,node/3117171644,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 2998732, ""reltags"":...",False,POINT (9.7219 52.36216),"[#0069B4, #76B82A, #0069B4, #0069B4]","[13, 17, 3, 7]",Allerweg,"[373.4600830078125, 388.48046875, 394.82775878...","(372.7162780761719, 352.1495819091797)",36.338500
3,Alte Heide,"MULTIPOINT (9.78078 52.41546, 9.78083 52.41557)",node/1343306077,node/1343306077,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11002, ""...",False,POINT (9.7808 52.41551),[#E4003A],[2],Alte Heide,"[609.2645263671875, 101.68644714355469, 641.76...","(596.2845153808594, 116.70870590209961)",13.492200
4,Altenbekener Damm,"MULTIPOINT (9.75451 52.35488, 9.75459 52.3549)",node/96716127,node/96716127,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 2995651, ""reltags"":...",False,POINT (9.75455 52.35489),"[#E4003A, #E4003A, #E4003A]","[1, 2, 8]",Altenbekener Damm,"[400.19244384765625, 385.8978271484375, 449.34...","(452.6719055175781, 390.32579040527344)",3.328186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Wissenschaftspark Marienwerder,"MULTIPOINT (9.63369 52.41621, 9.63372 52.41617)",node/287015667,node/287015667,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 2951396, ""reltags"":...",False,POINT (9.63371 52.41619),[#F9B000],[4],Wissenschaftspark Marienwerder,"[247.4655303955078, 53.948795318603516, 310.84...","(264.5452117919922, 118.46560287475586)",1.139515
200,Wunstorfer Straße,"MULTIPOINT (9.69509 52.37522, 9.6952 52.37524)",node/29364435,node/29364435,None,yes,yes,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 11012, ""reltags"": {...",False,POINT (9.69514 52.37523),"[#76B82A, #76B82A]","[10, 12]",Wunstorfer Str.,"[245.119140625, 285.39495849609375, 277.260833...","(249.10289764404297, 318.67572021484375)",1.139069
201,Zehlendorfweg,"MULTIPOINT (9.75863 52.41967, 9.75974 52.41947)",node/248004234,node/248004234,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 2998554, ""reltags"":...",False,POINT (9.75919 52.41957),[#E4003A],[2],Zehlendorfweg,"[574.236083984375, 141.38613891601562, 610.928...","(570.450927734375, 142.42351531982422)",3.785156
202,Zoo,"MULTIPOINT (9.76671 52.38118, 9.7668 52.38119)",node/137703451,node/137703451,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop_entry_only"", ""rel"": 11010, ""...",False,POINT (9.76675 52.38118),[#F9B000],[11],Zoo,"[574.135986328125, 263.43951416015625, 585.670...","(561.0580139160156, 278.7069091796875)",13.654938
203,Zuschlagstraße,"MULTIPOINT (9.79255 52.35679, 9.7926 52.35682)",node/243056543,node/243056543,None,None,None,None,None,NaT,...,None,"[ { ""role"": ""stop"", ""rel"": 10999, ""reltags"": {...",False,POINT (9.79257 52.35681),[#F9B000],[6],Zuschlagstr.,"[573.7821655273438, 382.080810546875, 602.6842...","(570.025634765625, 389.49107360839844)",3.756531

### Transformation der Koordinaten vom Netzplan auf die GPS-Koordinaten aus dem Dataframe

als nächstes die quad_rect_text irgendwie "skalieren", damit ich das auf die Karte mappen kann.
also sowas wie: "Endstation Garbsen quad_rect_text"=='Koordinaten aus dem gdf dataframe"
das für alle/einige End-Stationen machen. Außerdem am Kröpcke zentrieren.
oder sowas wie "min/max rect aus den circles". min/max ist dann an den min/max-GeoKoordinaten ausgerichtet.

In [398]:
# Maske: Zeilen, in denen GPS vorhanden ist (Basis für die Kalibrierung)
mask_known = gdf_stations["nearest_point"].notna()

# Individuelle Koordinaten zerlegen

# df['B'].apply(lambda p: [y[0] for y in p])

x_indiv = gdf_stations.loc[mask_known, "nearest_point"].str[0]#apply(lambda p: [y[0] for y in p])#.apply(lambda p: p[0])
y_indiv = gdf_stations.loc[mask_known, "nearest_point"].str[1]#apply(lambda p: [y[0] for y in p])#.apply(lambda p: p[0])
# y_indiv = gdf_stations.loc[mask_known, "nearest_point"].apply(lambda p: p[1])

# GPS zerlegen
lon = gdf_stations.loc[mask_known, "center"].x#apply(lambda p: p[0])
lat = gdf_stations.loc[mask_known, "center"].y# apply(lambda p: p[1])

# Min / Max der individuellen Skala
x_min, x_max = x_indiv.min(), x_indiv.max()
y_min, y_max = y_indiv.min(), y_indiv.max()

# Min / Max der GPS-Skala
lon_min, lon_max = lon.min(), lon.max()
lat_min, lat_max = lat.min(), lat.max()


def map_x_to_lon(x):
    if x_max == x_min:
        return np.nan   # degenerierter Fall, zur Sicherheit
    return lon_min + (x - x_min) * (lon_max - lon_min) / (x_max - x_min)

def map_y_to_lat(y):
    if y_max == y_min:
        return np.nan
    return lat_min + (y - y_min) * (lat_max - lat_min) / (y_max - y_min)


def map_indiv_to_gps(indiv_pt):
    if not isinstance(indiv_pt, (list, tuple)) or len(indiv_pt) != 2:
        return np.nan#, np.nan)
    x, y = indiv_pt

    # p = Point(1.0, -1.0)

    # geometry = geopandas.points_from_xy(df.longitude, df.latitude, crs="EPSG:4326")
    return shapely.Point(map_x_to_lon(x), map_y_to_lat(y))

gdf_stations["netzplan_gps_mapped"] = gdf_stations["nearest_point"].apply(map_indiv_to_gps)

In [399]:
type(gdf_stations["netzplan_gps_mapped"][0])
type(gdf_stations["center"][0])

shapely.geometry.point.Point

In [406]:
# jetzt die beiden Punkte zusammen in folio mappen:

m = folium.Map(location=list(reversed(homebase)), tiles='cartodbpositron', zoom_start=13)

# Linien:
for _, line in gdf_lines.iterrows():
    my_PolyLine=folium.PolyLine(locations=line["coordinates"], weight=4,
                                color=line["colour"],
                                tooltip=line["name"])
    my_PolyLine.add_to(m)

# Stationen:
for _, r in gdf_stations.iterrows():
    lat = r["center"].y
    lon = r["center"].x

    # falls vorhanden, nimm immer die erste Farbe in der Liste:
    if isinstance(r["reltags_colours"], list) and len(r["reltags_colours"]) > 0:
        farbe_station= r["reltags_colours"][0]
        #print(f"name: {r['name']}, {farbe_station}")

    else:
       farbe_station =  "#000000"

    # Linien nach Nummern sortieren
    def sort_linerefs(refs):
        sorted_lines = sorted([int(x) for x in refs])
        return sorted_lines

    if isinstance(r["reltags_refs"], list):
        # sortiere als int, convert whole list to str and then entferne die Listen-Klammern hinten und vorne ([1:-1])
        lines =  str(sort_linerefs(r["reltags_refs"]))[1:-1]
    else:
        lines ="Keine Linien"

    folium.CircleMarker(
        location=[lat, lon],
        popup="<strong>{}</strong><br><br> Linien: {}".format(r["name"],lines),
        color=farbe_station,
        fill_color=farbe_station,
        fill_opacity=1,
        radius=4
    ).add_to(m)

# jetzt aus dem netzplan:
for _, r in gdf_stations.iterrows():
    #print(r["netzplan_gps_mapped"])
    if type(r["netzplan_gps_mapped"]) == float and pd.isna(r["netzplan_gps_mapped"]):
        #print('do A')
        continue
    lat = r["netzplan_gps_mapped"].y
    lon = r["netzplan_gps_mapped"].x

    # falls vorhanden, nimm immer die erste Farbe in der Liste:
    if isinstance(r["reltags_colours"], list) and len(r["reltags_colours"]) > 0:
        farbe_station= r["reltags_colours"][0]
        #print(f"name: {r['name']}, {farbe_station}")

    else:
       farbe_station =  "#000000"

    # Linien nach Nummern sortieren
    def sort_linerefs(refs):
        sorted_lines = sorted([int(x) for x in refs])
        return sorted_lines

    if isinstance(r["reltags_refs"], list):
        # sortiere als int, convert whole list to str and then entferne die Listen-Klammern hinten und vorne ([1:-1])
        lines =  str(sort_linerefs(r["reltags_refs"]))[1:-1]
    else:
        lines ="Keine Linien"

    folium.CircleMarker(
        location=[lat, lon],
        popup="<strong>{}</strong><br><br> Linien: {}".format(r["name"],lines),
        color=farbe_station,
        fill_color='black',
        fill_opacity=1,
        radius=4
    ).add_to(m)
m

## Nächste Schritte:
den Kröpcke noch mal als Center setzen, damit es nicht _nur_ min/max skaliert ist.
danach: distanzen berechnen / warpen
bzw: direkt das GPS entsprechend der individuellen Distanzen aus dem Netzplan warpen.

außerdem noch: die bisher nicht abgebildeten Stationen aus dem Netzplan (Kröpcke, Hbf etc.) noch mit einbinden.

In [403]:
# # jetzt mal schauen, wie die quads aussehen; kann man daraus irgendwie die Koordinaten (sinnvoll) ableiten?
# # manchmal ist der Punkt links, rechts, unterschiedlich..
#
# doc = fitz.open("UESTRA_Netzplan-U_2024-25.pdf")
# page = doc[0]  # es gibt nur eine Seite
# page_rect = page.rect
#
# rl_name = page.search_for('Lister Platz', quads=True)[0]
# print(rl_name)
# #print(rl_name.ll)#.is_rectangular)
#
# # page.add_highlight_annot(rl_name)
# annot = page.add_caret_annot(rl_name.ll)
# annot = page.draw_circle(rl_name.ll, 2, color=(0,1,0))
# annot = page.draw_circle(rl_name.ul, 2, color=(0,0,1))
#
# page.draw_circle(fitz.Point(gdf_stations['nearest_point'].iloc[128]), 5, color=(1,0,0))
# print(gdf_stations['nearest_point'].iloc[128])
# print(rl_name.ul)
#
# # annot = page.draw_circle(fitz.Point(519.6, 239.2), 2, color=(1,0,0))
# # annot = page.draw_circle(fitz.Point(454.4718933105469, 261.8717041015625), 5, color=(1,0,0))
#
#
# # for c in circles:
# #     annot = page.draw_circle(fitz.Point(c), 5, color=(1,0,0))
#
# # die gleichen wie circles, nur halt die bboxes dazu.
# # for r in rects:
# #     page.add_highlight_annot(fitz.Rect(r))
#
# # jetzt die bbox vergrößern
# width = rl_name.width
# height = rl_name.height
#
# def getPolygon(quad, scale=1):
#     [sumX, sumY] = [0, 0]
#     for point in quad:
#         sumX += point[0]
#         sumY += point[1]
#     avgX = sumX/4
#     avgY = sumY/4
#
#     # Scale the rectange using Quad.morph(): https://pymupdf.readthedocs.io/en/latest/quad.html#Quad.morph
#     quad= quad.morph(fitz.Point(avgX,  avgY), fitz.Matrix(scale, scale))
#     return quad
#
# # print(getPolygon(rl_name, 5)
# scaled = getPolygon(rl_name, 1.2).rect
# #print(scaled.rect)
# page.add_highlight_annot(scaled)
#
#
# doc.save("output.pdf", garbage=4, deflate=True, clean=True)

### Alter Code:

In [61]:
# since folio and the routing take different polygon/coordinate formats, we use polygon_coords and polygon_geom to store the polygon information
# folio: list of list containing tuples
# routing: MultiPolygon Object


# for each lat/long-list: create polygon, add to list and add coordinates to a separate list
# after that, create MultiPolygon from all Polygons

regions = [([10.5288243, 10.522855, 10.524474, 10.5398],[52.2733412, 52.265497, 52.264311, 52.2707]),
           ([10.5146, 10.522855, 10.524474, 10.5398],[52.270, 52.265497, 52.264311, 52.2707])]

polygon_coords = [] # coordinates are stored for folio
polygon_geom = [] # list of Polygon objects

for lon, lat in regions:
    polygon_coord = list(zip(lon, lat))
    polygon_geom.append(Polygon(polygon_coord))
    polygon_coord = [(y, x) for x, y in polygon_coord]  # Reverse coords for folium
    polygon_coords.append(polygon_coord)

polygons = MultiPolygon([p for p in polygon_geom])

# iterate over MultiPolygon (example)
# for poly in polygons.geoms:
#     print(poly)